### ISSUE TITLE
3.2.0 jar in wrong bintray directory?

### ISSUE THREAD

**Issue by garyhodgson** [t1/logging-interceptor#29]
Hi

It seems the 3.2.0 jar file is in the wrong folder in bintray.  Instead of being in https://dl.bintray.com/t1/javaee-helpers/com/github/t1/logging-interceptor/ it appears to be in https://dl.bintray.com/t1/javaee-helpers/

Consequently Maven cannot find it, e.g. via a nexus remote repository.

**Comment by t1** [comment]
@garyhodgson: Thanks for the feedback, I hadn't noticed! Javadoc and source are also missing. I wonder what went wrong. I just tried a new release and Bintray threw a 400 Bad Request. I'm investigating.

**Comment by t1** [comment]
@garyhodgson: Now it should work. Try 3.2.2. Thanks again for the feedback.
